server:
  port: ${PORT:8080}

spring:
  application:
    name: Employee-Tracking-System

  datasource:

    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
    show-sql: true

  jackson:
    time-zone: Asia/Kolkata

  main:
    allow-circular-references: true
    
