server:
  port: ${PORT:8080}

spring:
  application:
    name: Employee-Tracking-System

  datasource:
    url: jdbc:postgresql://ep-royal-art-adx5q10k-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_huze47QcRasm

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
    show-sql: true

  jackson:
    time-zone: Asia/Kolkata

  main:
    allow-circular-references: true
