server:
  port: 8080

spring:
  application:
    name: Employee-Tracking-System

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  main:
    allow-circular-references: true
