server:
   port: ${PORT:8080}

spring:
   application:
      name: Employee-Tracking-System

   datasource:
      url: jdbc:postgresql://ep-falling-mud-afu77gy8-pooler.c-2.us-west-2.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
      username: neondb_owner
      password: npg_Zw29qCPMmJSB
      driver-class-name: org.postgresql.Driver

   jpa:
      hibernate:
         ddl-auto: update
         jdbc:
            time_zone: Asia/Kolkata
      show-sql: true
      repositories:
         bootstrap-mode: lazy

   jackson:
      time-zone: Asia/Kolkata

   main:
      allow-circular-references: true