server:
   port: ${PORT:8080}

spring:
   application:
      name: Employee-Tracking-System

   datasource:
      url: jdbc:postgresql://ep-green-block-aem0hfok-pooler.c-2.us-east-2.aws.neon.tech/neondb
      username: neondb_owner
      password: npg_bWGRz8VMCn4D
      driver-class-name: org.postgresql.Driver

   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            jdbc:
               time_zone: Asia/Kolkata
      show-sql: true

   jackson:
      time-zone: Asia/Kolkata

   main:
      allow-circular-references: true

   data:
      jpa:
         repositories:
            bootstrap-mode: lazy