server:
  port: 8080

spring:
  application:
    name: Employee-Tracking-System

  datasource:
    url: jdbc:postgresql://ep-fancy-rice-a859181v-pooler.eastus2.azure.neon.tech:5432/Employee-track?sslmode=require
    username: Employee-track_owner
    password: npg_ONC8zRT4EtrH

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  main:
    allow-circular-references: true
