server:
   port: ${PORT:8080}

spring:
   application:
      name: Employee-Tracking-System

   datasource:
      url: jdbc:postgresql://ep-falling-mud-afu77gy8-pooler.c-2.us-west-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_Zw29qCPMmJSB&sslmode=require&channelBinding=require
      username: neondb_owner
      password: npg_Zw29qCPMmJSB
      driver-class-name: org.postgresql.Driver

   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            jdbc:
               time_zone: Asia/Kolkata
      show-sql: true

   jackson:
      time-zone: Asia/Kolkata

   main:
      allow-circular-references: true

   data:
      jpa:
         repositories:
            bootstrap-mode: lazy