server:
  port: ${PORT:8080}

spring:
  application:
    name: Employee-Tracking-System

  datasource:
    url: jdbc:postgresql://ep-super-dust-adns4tzr-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_JH0dwV2ORjDK
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: Asia/Kolkata
    show-sql: true
    open-in-view: false
    repositories:
      bootstrap-mode: lazy

  jackson:
    time-zone: Asia/Kolkata

  main:
    allow-circular-references: true