server:
   port: ${PORT:8080}

spring:
   application:
      name: Employee-Tracking-System

   datasource:
      url: jdbc:postgresql://ep-falling-mud-afu77gy8-pooler.c-2.us-west-2.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
      username: neondb_owner
      password: npg_Zw29qCPMmJSB
      driver-class-name: org.postgresql.Driver

<<<<<<< HEAD
   jpa:
      hibernate:
         ddl-auto: update
         jdbc:
            time_zone: Asia/Kolkata
      show-sql: true
      repositories:
         bootstrap-mode: lazy
=======
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: Asia/Kolkata
    show-sql: true
    repositories:
      bootstrap-mode: lazy
>>>>>>> 7a4adb49aaa91529843a06f42830f16b76519d23

   jackson:
      time-zone: Asia/Kolkata

<<<<<<< HEAD
   main:
      allow-circular-references: true
=======
  main:
    allow-circular-references: true
>>>>>>> 7a4adb49aaa91529843a06f42830f16b76519d23
